apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  keycloak-db-config: |
    {
      "datasources": [
        {
          "name": "KeycloakDS",
          "driver": "postgresql",
          "connectionUrl": "jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)",
          "username": "$(POSTGRES_USER)",
          "password": "$(POSTGRES_PASSWORD)",
          "jndi": "java:jboss/datasources/KeycloakDS",
          "enabled": true,
          "useJavaContext": true
        }
      ]
    }