apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8282
      targetPort: 8282
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.1.1
          args: ["start-dev"]
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: "192.168.2.231"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "db_auth"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: ""
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080

# apiVersion: v1
# kind: Service
# metadata:
#   name: keycloak-service
#   namespace: keycloak
#   labels:
#     app: keycloak
# spec:
#   ports:
#     - name: http
#       port: 8282
#       targetPort: 8282
#   selector:
#     app: keycloak
#   type: NodePort
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: keycloak
#   namespace: keycloak
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: keycloak
#   template:
#     metadata:
#       labels:
#         app: keycloak
#     spec:
#       containers:
#         - name: keycloak
#           image: jboss/keycloak:latest
#           envFrom:
#             - configMapRef:
#                 name: keycloak-postgres-config
#             - secretRef:
#                 name: keycloak-postgres-credentials
#           ports:
#             - name: http
#               containerPort: 8282
#           readinessProbe:
#             httpGet:
#               path: /realms/master
#               port: 8282
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.1.1
          # env:
          #   - name: DB_VENDOR
          #     value: POSTGRES
          #   - name: DB_ADDR
          #     valueFrom:
          #       secretKeyRef:
          #         name: keycloak-postgres
          #         key: POSTGRES_HOST
          #   - name: DB_PORT
          #     valueFrom:
          #       secretKeyRef:
          #         name: keycloak-postgres
          #         key: POSTGRES_PORT
          #   - name: DB_DATABASE
          #     valueFrom:
          #       secretKeyRef:
          #         name: keycloak-postgres
          #         key: POSTGRES_DB
          #   - name: DB_USER
          #     valueFrom:
          #       secretKeyRef:
          #         name: keycloak-postgres
          #         key: POSTGRES_USER
          #   - name: DB_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: keycloak-postgres
          #         key: POSTGRES_PASSWORD

          args: ["start-dev"]
          env:
            # - configMapRef:
            #     name: postgres-config
            # - secretRef:
            #     name: postgres-credentials
            - name: KC_PROXY
              value: "edge"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:21.1.1
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
