apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: keycloak-service
#   namespace: keycloak
#   labels:
#     app: keycloak
# spec:
#   ports:
#     - port: 53582
#       targetPort: 80
#   selector:
#     app: keycloak
